// <auto-generated />
using System;
using FinalProject_PRN222_Group7.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_PRN222_Group7.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714071059_AddBillingWalletAiCredit")]
    partial class AddBillingWalletAiCredit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.AiActionCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ActionCode")
                        .IsUnique();

                    b.ToTable("AiActionCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionCode = "chat.ask",
                            ActionName = "Hỏi đáp AI",
                            CreditCost = 1,
                            Description = "Mỗi lượt hỏi chat AI tiêu tốn 1 credit.",
                            DisplayOrder = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ActionCode = "quiz.generate",
                            ActionName = "Sinh quiz bằng AI",
                            CreditCost = 5,
                            Description = "Sinh một bài quiz từ tài liệu tiêu tốn 5 credit.",
                            DisplayOrder = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ActionCode = "flashcard.generate",
                            ActionName = "Sinh flashcard",
                            CreditCost = 3,
                            Description = "Sinh flashcard từ tài liệu tiêu tốn 3 credit.",
                            DisplayOrder = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ActionCode = "summary.generate",
                            ActionName = "Tóm tắt tài liệu",
                            CreditCost = 2,
                            Description = "Tóm tắt tài liệu tiêu tốn 2 credit.",
                            DisplayOrder = 4,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.AiUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreditTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("CreditsCharged")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreditTransactionId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AiUsageLogs");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserPackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserPackageId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.BenchmarkRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AnswerRelevancy")
                        .HasColumnType("float");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<string>("ChunkingStrategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ContextPrecision")
                        .HasColumnType("float");

                    b.Property<double>("ContextRecall")
                        .HasColumnType("float");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Faithfulness")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallAccuracy")
                        .HasColumnType("float");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BenchmarkRuns");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SourceCitations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LegacyAppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LegacyAppUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LegacyAppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("LegacyAppUserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CreditPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "credit-500",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 500,
                            Description = "Bổ sung nhanh cho các tác vụ học tập hằng ngày.",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = false,
                            Name = "500 AI Credit",
                            Price = 29000m,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "credit-1500",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 1500,
                            Description = "Gói tiết kiệm cho kỳ học có cường độ sử dụng AI cao.",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Name = "1.500 AI Credit",
                            Price = 79000m,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "credit-4000",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 4000,
                            Description = "Phù hợp khi cần học tăng tốc hoặc ôn thi dài hạn.",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = false,
                            Name = "4.000 AI Credit",
                            Price = 179000m,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditWalletId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditWalletId");

                    b.HasIndex("RequestId");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternalCreditBalance")
                        .HasColumnType("int");

                    b.Property<int>("PurchasedCreditBalance")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SubscriptionCreditBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CreditWallets");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UploadedByUserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CourseId");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasBenchmark")
                        .HasColumnType("bit");

                    b.Property<bool>("HasQuizGeneration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDocuments")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyAiQueries")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyCredit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingPeriod = 1,
                            Code = "legacy-basic",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói cũ để giữ tương thích dữ liệu hiện tại.",
                            DisplayOrder = 90,
                            DurationInDays = 30,
                            HasBenchmark = false,
                            HasQuizGeneration = false,
                            IsActive = false,
                            IsFeatured = false,
                            IsFree = true,
                            MaxDocuments = 5,
                            MonthlyAiQueries = 50,
                            MonthlyCredit = 50,
                            Name = "Basic (Legacy)",
                            Price = 0m,
                            Tier = 0,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BillingPeriod = 1,
                            Code = "legacy-pro",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói cũ để giữ tương thích dữ liệu hiện tại.",
                            DisplayOrder = 91,
                            DurationInDays = 30,
                            HasBenchmark = false,
                            HasQuizGeneration = true,
                            IsActive = false,
                            IsFeatured = false,
                            IsFree = false,
                            MaxDocuments = 50,
                            MonthlyAiQueries = 500,
                            MonthlyCredit = 500,
                            Name = "Pro (Legacy)",
                            Price = 99000m,
                            Tier = 1,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BillingPeriod = 1,
                            Code = "legacy-ultra",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói cũ để giữ tương thích dữ liệu hiện tại.",
                            DisplayOrder = 92,
                            DurationInDays = 30,
                            HasBenchmark = true,
                            HasQuizGeneration = true,
                            IsActive = false,
                            IsFeatured = false,
                            IsFree = false,
                            MaxDocuments = -1,
                            MonthlyAiQueries = -1,
                            MonthlyCredit = 2000,
                            Name = "Ultra (Legacy)",
                            Price = 299000m,
                            Tier = 2,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BillingPeriod = 1,
                            Code = "free",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói miễn phí cho sinh viên với credit cơ bản hằng tháng.",
                            DisplayOrder = 1,
                            DurationInDays = 30,
                            HasBenchmark = false,
                            HasQuizGeneration = false,
                            IsActive = true,
                            IsFeatured = false,
                            IsFree = true,
                            MaxDocuments = 0,
                            MonthlyAiQueries = 50,
                            MonthlyCredit = 50,
                            Name = "Free",
                            Price = 0m,
                            Tier = 3,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BillingPeriod = 1,
                            Code = "basic",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phù hợp cho sinh viên cần dùng AI thường xuyên trong một môn học.",
                            DisplayOrder = 2,
                            DurationInDays = 30,
                            HasBenchmark = false,
                            HasQuizGeneration = true,
                            IsActive = true,
                            IsFeatured = false,
                            IsFree = false,
                            MaxDocuments = 0,
                            MonthlyAiQueries = 250,
                            MonthlyCredit = 250,
                            Name = "Basic",
                            Price = 49000m,
                            Tier = 0,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BillingPeriod = 1,
                            Code = "plus",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói phổ biến nhất cho sinh viên dùng chat, quiz và phân tích học tập nâng cao.",
                            DisplayOrder = 3,
                            DurationInDays = 30,
                            HasBenchmark = false,
                            HasQuizGeneration = true,
                            IsActive = true,
                            IsFeatured = true,
                            IsFree = false,
                            MaxDocuments = 0,
                            MonthlyAiQueries = 800,
                            MonthlyCredit = 800,
                            Name = "Plus",
                            Price = 99000m,
                            Tier = 4,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BillingPeriod = 1,
                            Code = "research",
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói cao nhất cho nhu cầu nghiên cứu, tổng hợp và phân tích AI chuyên sâu.",
                            DisplayOrder = 4,
                            DurationInDays = 30,
                            HasBenchmark = true,
                            HasQuizGeneration = true,
                            IsActive = true,
                            IsFeatured = false,
                            IsFree = false,
                            MaxDocuments = 0,
                            MonthlyAiQueries = 2000,
                            MonthlyCredit = 2000,
                            Name = "Research",
                            Price = 199000m,
                            Tier = 5,
                            UpdatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.PackageFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "FeatureCode")
                        .IsUnique();

                    b.ToTable("PackageFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            FeatureCode = "ai.chat.single_kb",
                            FeatureName = "Chat AI theo môn học",
                            FeatureValue = "basic",
                            IsEnabled = true,
                            PackageId = 10
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            FeatureCode = "ai.quiz.basic",
                            FeatureName = "Làm quiz AI",
                            FeatureValue = "false",
                            IsEnabled = false,
                            PackageId = 10
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            FeatureCode = "ai.chat.single_kb",
                            FeatureName = "Chat AI theo môn học",
                            FeatureValue = "standard",
                            IsEnabled = true,
                            PackageId = 11
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 2,
                            FeatureCode = "ai.quiz.basic",
                            FeatureName = "Sinh quiz cơ bản",
                            FeatureValue = "true",
                            IsEnabled = true,
                            PackageId = 11
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            FeatureCode = "ai.chat.multi_doc",
                            FeatureName = "Chat AI đa tài liệu",
                            FeatureValue = "true",
                            IsEnabled = true,
                            PackageId = 12
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            FeatureCode = "ai.quiz.basic",
                            FeatureName = "Sinh quiz AI",
                            FeatureValue = "true",
                            IsEnabled = true,
                            PackageId = 12
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            FeatureCode = "ai.flashcard.basic",
                            FeatureName = "Flashcard AI",
                            FeatureValue = "true",
                            IsEnabled = true,
                            PackageId = 12
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            FeatureCode = "ai.deep_analysis",
                            FeatureName = "Phân tích AI chuyên sâu",
                            FeatureValue = "true",
                            IsEnabled = true,
                            PackageId = 13
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 2,
                            FeatureCode = "benchmark.advanced",
                            FeatureName = "Benchmark nâng cao",
                            FeatureValue = "true",
                            IsEnabled = true,
                            PackageId = 13
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 3,
                            FeatureCode = "priority.processing",
                            FeatureName = "Ưu tiên xử lý",
                            FeatureValue = "high",
                            IsEnabled = true,
                            PackageId = 13
                        });
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreditPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayOrderCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyAppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditPackageId");

                    b.HasIndex("GatewayOrderCode")
                        .IsUnique()
                        .HasFilter("[GatewayOrderCode] IS NOT NULL");

                    b.HasIndex("LegacyAppUserId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.PaymentCallbackLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayOrderCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GatewayProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSignatureValid")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("GatewayProvider", "GatewayOrderCode", "Signature");

                    b.ToTable("PaymentCallbackLogs");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.QuestionBankItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DocumentId");

                    b.ToTable("QuestionBankItems");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<int?>("LegacyCourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseId1");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LegacyCourseId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("LegacyAppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyAppUserId");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.UploadLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedByFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UploadLogs");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.UserPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQueries")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPackages");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NextPackageId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NextPackageId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.AiUsageLog", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.CreditTransaction", "CreditTransaction")
                        .WithMany()
                        .HasForeignKey("CreditTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithMany("AiUsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.AppUser", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.UserPackage", "UserPackage")
                        .WithMany()
                        .HasForeignKey("UserPackageId");

                    b.Navigation("UserPackage");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Chapter", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.ChatMessage", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.ChatSession", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("LegacyAppUserId")
                        .HasConstraintName("FK_ChatSessions_AspNetUsers_AppUserId");

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Course", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "Lecturer")
                        .WithMany("Courses")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("LegacyAppUserId")
                        .HasConstraintName("FK_Courses_AspNetUsers_AppUserId");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditTransaction", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.CreditWallet", "CreditWallet")
                        .WithMany("Transactions")
                        .HasForeignKey("CreditWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditWallet");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditWallet", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithOne("CreditWallet")
                        .HasForeignKey("FinalProject_PRN222_Group7.DAL.Entities.CreditWallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Document", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Course", "Course")
                        .WithMany("Documents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Course");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.DocumentChunk", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.PackageFeature", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Package", "Package")
                        .WithMany("Features")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Payment", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.CreditPackage", "CreditPackage")
                        .WithMany("Payments")
                        .HasForeignKey("CreditPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("LegacyAppUserId")
                        .HasConstraintName("FK_Payments_AspNetUsers_AppUserId");

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.UserSubscription", "UserSubscription")
                        .WithMany("Payments")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreditPackage");

                    b.Navigation("Package");

                    b.Navigation("User");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.PaymentCallbackLog", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Payment", "Payment")
                        .WithMany("CallbackLogs")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Question", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.QuestionBankItem", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Chapter", "Chapter")
                        .WithMany("QuestionBankItems")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("Course");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Quiz", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Course", "Course")
                        .WithMany("Quizzes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("LegacyCourseId")
                        .HasConstraintName("FK_Quizzes_Courses_CourseId1");

                    b.Navigation("Course");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.QuizAttempt", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("LegacyAppUserId")
                        .HasConstraintName("FK_QuizAttempts_AspNetUsers_AppUserId");

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.UserPackage", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Package", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.UserSubscription", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Package", "NextPackage")
                        .WithMany()
                        .HasForeignKey("NextPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.Package", "Package")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NextPackage");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FinalProject_PRN222_Group7.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.AppUser", b =>
                {
                    b.Navigation("AiUsageLogs");

                    b.Navigation("ChatSessions");

                    b.Navigation("Courses");

                    b.Navigation("CreditWallet");

                    b.Navigation("Payments");

                    b.Navigation("QuizAttempts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Chapter", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("QuestionBankItems");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Documents");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditPackage", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.CreditWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Package", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Payment", b =>
                {
                    b.Navigation("CallbackLogs");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FinalProject_PRN222_Group7.DAL.Entities.UserSubscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
